apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
{{ include "mariadb.labels" . | indent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ default "" .Values.mariadbRootPassword | b64enc | quote }}
  mariadb-password: {{ default "" .Values.mariadbRootPassword | b64enc | quote }}
