version: '2'

services:
    db:
        image: clearlinux/mariadb:latest
        restart: always
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: clear
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        networks:
            - code-network
    nginx:
        image: clearlinux/nginx:latest
        ports:
            - "8080:80"
        links:
            - wordpress
        volumes:
            - html:/var/www/html 
            - ./wordpress.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    wordpress:
        depends_on:
            - db
        image: clearlinux/wordpress:latest
        restart: always
        volumes:
            - html:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: clear
            WORDPRESS_DB_PASSWORD: 1234
            WORDPRESS_DB_NAME: wordpress
        command: php-fpm
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
volumes:
        html:
